version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
    interval: "daily"
    allow:
      -dependency-type: "production"
    ignore:
      - dependency-name: "*"
        update-types:
          ["version-update:semver-patch", "version-update:semver-minor"]
  - package-ecosystem: cargo
    directory: "/contract"
    schedule:
      interval: "daily"
