name: fmt

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  fmt:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: contracts
    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt

      - uses: actions/checkout@v4

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Run fmt
        run: cargo +nightly fmt --verbose -- --check
