name: Spellcheck

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  spellcheck:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    env:
      working-directory: ./contract
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    container:
      image: "paritytech/ink-waterfall-ci:latest"
    steps:
      - name: Run spellcheck
        shell: bash
        run: cargo spellcheck check -vvvv --cfg=.config/cargo_spellcheck.toml --checkers hunspell --code 1
