name: Spellcheck

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  spellcheck:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: contract
    container:
      image: "paritytech/ci-unified:bullseye-1.75.0"
    steps:
      - uses: actions/checkout@v4
      - name: Run spellcheck
        shell: bash
        run: |
          cargo spellcheck check -vvvv --cfg=.config/cargo_spellcheck.toml --checkers hunspell --code 1
